### ISSUE TITLE
Add profile settings to Dashboard

### ISSUE THREAD

**Issue by eden-chan** [LemonFace0309/Study-Space#102]
- [x] Add column for profile settings

**Comment by mabelene** [comment]
![image](https://user-images.githubusercontent.com/39652186/126249228-e7a31279-90a7-4370-85dc-cbe8ba9af2d3.png)

**Comment by mabelene** [comment]
new:
![image](https://user-images.githubusercontent.com/39652186/126249256-568c5b18-bf48-448e-8ff1-c3cc2a729156.png)

**Comment by mabelene** [comment]
newer version: 
![image](https://user-images.githubusercontent.com/39652186/126257642-f7baf50e-55a5-4c7a-9d87-a041b0c6ca06.png)
